Form validation
EldinGuzin/yt_clone pull request #2
Opened 2024-07-16 11:55 UTC by EldinGuzin

2024-07-16 14:18 UTC, dixpac reviewed
Nice! Ostavio sam par komentara

2024-07-16 14:18 UTC, dixpac commented on app/models/post.rb
> +  validates :title, uniqueness: true
Jesi siguran da title treba biti unique, ako gledam ovo kao YT platformu onda mi ima smisla da moze biti videa sa istim nazivima?

Eventualno da je unique po useru da 1 user ne moze imati 2 videa sa istim nazivom

2024-07-16 14:18 UTC, dixpac commented on app/models/post.rb
> +  # validates :title, length: {minimum: 5}
✂️ skini komentare, komentarisan kod nema mejsto na main branchu

2024-07-16 14:18 UTC, dixpac commented on app/models/post.rb
> +  validate :image_content_type
👍

2024-07-16 14:35 UTC, EldinGuzin commented on app/models/post.rb
> +  validates :title, uniqueness: true
slazem se, uklonit cu uniqueness...

2024-07-17 07:06 UTC, dixpac commented on app/models/post.rb
> +
Format i spacing nevalja, kod treba da je lijep za citati kao da citas knjigu, treba izgledati na ovaj fazon
```ruby
class Post < ApplicationRecord
  belongs_to :user
  has_many :comments, dependent: :destroy

  has_one_attached :image
  has_one_attached :video

  validates :title, :description, presence: true
  validate :image_content_type
  validate :video_content_type

  private
    def image_content_type
      if image.attached? && !image.content_type.in?(%w(image/jpeg image/png))
        errors.add(:image, 'must be a JPEG or PNG')
      end
    end

    def video_content_type
      if video.attached? && !video.content_type.in?(%w(video/mp4))
        errors.add(:video, 'must be an MP4')
      end
    end
end
```

2024-07-17 07:07 UTC, dixpac requested changes
Jos jedan komentar oko formata koda, moras voditi recuna da je kod pedantno poslozen a ne nabacan. Pises kod koji drugi ljudi mogu citati kasnije, kod pises za ljude a ne masine

2024-07-23 07:56 UTC, merged