User changes
EldinGuzin/yt_clone pull request #3
Opened 2024-07-16 12:54 UTC by EldinGuzin

2024-07-16 14:22 UTC, dixpac requested changes
Thnx! Ostavio sam par zamijerki, prvenstveno oko reusanja nacina kako se rennda partial

2024-07-16 14:22 UTC, dixpac commented on app/views/posts/show.html.erb
> +          <% end %>
Posto avatar korisnika se koristi vjertovatno negdje u cosku na profilu, koristi se na komentarima.
Ekstraktuj rendanje avatara u rails helper pa onda moze koristi kroz cijeli app da imas api na ovaj fazon

`<%= render_avatar_for user %>`

Takodjer, moras napraviti use case kada korisnik nema avatar uploadan, sta da mu se pokaze, mozda je najbolje neki skraceni fazon sto bude tipa DM, EG, ili prvo slovo usernamea nesto na taj fazon

2024-07-17 07:14 UTC, dixpac requested changes

2024-07-17 07:14 UTC, dixpac commented on app/helpers/application_helper.rb
> +  def render_avatar_for(user, options = {})
Ovome je mjesto unutar `UsersHelper` modula.

Dodatno metoda je malo cudna, ukoliko imas base klasu za avattare a to je `rounded-circle img-thumbnail` zasto je proslijedjivati neka se ona doda unutar helpera. Sta je `avatar` css klasa?

Velicine 50 i brojevi nisu bas citljivi napravi par velicina npr: `sm, md, lg` pa onda api moze izgledati ovako

`render_avatar_for user, size: :lg` 
`render_avatar_for user, class: "mr-3", size: :sm` 

Sta nekome ko koristi methodu znaci 50 :), sm, md,lg imaju bolje znacenje

2024-07-18 11:28 UTC, EldinGuzin commented on app/helpers/application_helper.rb
> +  def render_avatar_for(user, options = {})
oke, ima smisla, ja sam dodao avatar css klasu jer sam kontao da dodam css properties u aplication.css i da tako loadam odmah properties nego da pisem inline ali posto koristim bootstrap nece veliku razliku napraviti

2024-07-18 12:37 UTC, dixpac requested changes
Nice, jos samo jedna sitnica

2024-07-18 12:37 UTC, dixpac commented on app/helpers/application_helper.rb
> +           end
Ovo moze biti hash AVATAR_SIZES = { sm: 50, md: 100, lg: 150 } kojem onda pristupas
`AVATAR_SIZES[:sm]`. 
I rails image_tag helper ima metode height i witdh, provjer da li ti je width uopce potreban

2024-07-23 07:15 UTC, dixpac commented on app/controllers/application_controller.rb
> +  include AvatarHelper
Nema potrebe da includas helpere. Svaku helper je po defaultu includan to radi rails za tebe.
Dodatno helperi su u global namespacu, sto znaci da npr ako imas 2 razlicita helpera sa istim imenom metode moze jedan drugoga prepisati, zato treba paziti sa helperima da nemas iste nazive metoda

2024-07-23 08:04 UTC, merged